### ISSUE TITLE
m1-mac-mini-os12.3.1启动报错

### ISSUE THREAD

**Issue by shelken** [liumingye/bilimini#9]
Uncaught Exception:
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=101 uv=1 armv=8 libc=glibc
at Function.load.path (/Applications/webmini.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:56:9)
at load (/Applications/webmini.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:20:30)
at Object.<anonymous> (/Applications/webmini.app/Contents/Resources/app.asar/node_modules/leveldown/binding.js:1:43)
at Module._compile (node:internal/modules/cjs/loader:1116:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)

**Comment by shelken** [comment]
版本1.0.7
